### ISSUE TITLE
Remove Vue CLI Plugin Electron Builder

### ISSUE THREAD

**Issue by basil** [danielgarthur/neanes#116]
This library was last updated on June 24, 2021. Per https://github.com/nklayman/vue-cli-plugin-electron-builder/issues/1677 it does not support Webpack 5, precluding an upgrade to Vue CLI 5 (itself only slightly less of a dead end than Vue CLI 4), which in turn precludes an upgrade to ESLint 8. Per https://github.com/nklayman/vue-cli-plugin-electron-builder/issues/1959 it also does not support Node.js 18 and Electron 23. Clearly this dependency is a liability.

Per the [Vue.js tooling guide](https://vuejs.org/guide/scaling-up/tooling.html):

> [Vue CLI](https://cli.vuejs.org/) is the official webpack-based toolchain for Vue. It is now in maintenance mode and we recommend starting new projects with [Vite](https://vitejs.dev/) unless you rely on specific webpack-only features.

[Electron⚡️Vite](https://electron-vite.github.io/) appears to be the recommended tool for building a Vue.js 3 Electron application in 2023.

**Comment by basil** [comment]
I've been working on my own Vite branch for a while now at https://github.com/basil/neanes/tree/vite. I recently combined it with @danielgarthur's Vite branch at https://github.com/danielgarthur/neanes/tree/vite. I made some progress in a few areas, like getting the build running on Node 18 and migrating from VuePress to VitePress.

**Comment by W-Lawless** [comment]
Wow. No doubt the officials docs need to be updated to reflect this also.

**Comment by danielgarthur** [comment]
Awesome! Where I left off, dev mode and builds worked for electron and web, as did the installer (only tested in Windows). I was starting to look at [Vite-PWA](https://vite-pwa-org.netlify.app/) to add back the PWA functionality to the web version, but I don't consider this essential. I'd rather focus on getting the Electron app updated to Vue 3 and fix the web app in a later version since it's not the main focus of this project.

So really, all that remained was more testing, and updating the documentation and packages, which you've already started on.

**Comment by basil** [comment]
The production (Linux AppImage) build doesn't work for me on either my branch or yours. When I start the program, I just get the menus and a white screen. `npm run dev` does work for me though.

**Comment by basil** [comment]
The unit tests also failed for me until I switched from Jest to Vitest with globals enabled. I filed for another day any latent curiosity about why Vite appears intent on subsuming the entire JavaScript toolchain.

**Comment by basil** [comment]
> The production (Linux AppImage) build doesn't work for me on either my branch or yours. When I start the program, I just get the menus and a white screen. `npm run dev` does work for me though.

Fixed with

```ts
diff --git a/electron/main/index.ts b/electron/main/index.ts
index 5000179..e143353 100644
--- a/electron/main/index.ts
+++ b/electron/main/index.ts
@@ -1287,7 +1287,7 @@ async function createWindow() {
   } else {
     // Load the index.html when not in development
     autoUpdater.checkForUpdatesAndNotify();
-    await win.loadURL(indexHtml);
+    await win.loadFile(indexHtml);
   }
 }
```

**Comment by basil** [comment]
⇨ #150
