### ISSUE TITLE
Migrate from Vue.js 2 to 3

### ISSUE THREAD

**Issue by basil** [danielgarthur/neanes#117]
Per https://v2.vuejs.org/lts/ Vue 2 will reach End of Life (EOL) on December 31, 2023. Upstream recommends migrating to Vue 3: https://v3-migration.vuejs.org/

**Comment by basil** [comment]
I did a prototype upgrade to Vue 3 in https://github.com/basil/neanes/commit/7175d439c742e9a7a707f060741d1fc343092635 and learned a few things.

`vue-class-component` and `vue-property-decorator` have been replaced by `vue-facing-decorator`. It is a drop-in replacement, modulo changing the import from `vue-property-decorator` to `vue-facing-decorator`.

I could not find a suitable replacement for `vue-color` or `vue-draggable-resizable`, so for now I have simply deleted these dependencies and their callers, breaking the color picker and the ability to drag/resize images. Most likely these features will need to be reimplemented from scratch. At the moment I have no idea how to do this.

The most promising replacement for `vue-observe-visibility` seems to be `@uxieverity/vue3-observe-visibility`, but I could not get that package to work as described in its documentation. I also did not get a response to https://github.com/UxieVerity/vue3-observe-visibility/issues/1 when I asked for help. I did, however, get something working by copying and pasting the  `@uxieverity/vue3-observe-visibility` code into this repository (as `src/directives/observeVisibility.ts` and `src/utils/observeVisibility.ts` in the prototype) and making whatever changes were needed to pass our linter. I am not too sure about this one.

The `beforeDestroy` lifecycle event was renamed to `beforeUnmount`, a trivial string replacement.

Vue 3 requires each component to declare its emitted events. This was fairly straightforward, if laborious. Once events have been enumerated, usages of `.native` have to be deleted. I think this could be checked in to the Vue 2.x codebase today if desired, as Vue 2.x simply ignores this attribute.

`Vue.nextTick` has to be replaced with `nextTick`.

`src/main.ts` and `src/router.index.ts` needed a number of changes to adapt to new calling conventions of Vue 3 and Vue Router 4. The only issue I had here was that `component: Home` was failing with `TS2322: Type 'typeof import("node_modules/vue/dist/vue")' is not assignable to type 'RawRouteComponent | null | undefined`. I got that working by changing the line to `component: () => import('../views/Home.vue')` based on some example I found on the internet, but I am not sure if there is a better solution.

With all of the above changes the app starts and runs, though for some reason I cannot seem to scroll. That may or may not be related to the weirdness around `vue-observe-visibility`. Apart from the scrolling issue, the only other problems I observed were the broken color picker and lack of drag/resize support for images, which I fully expected to be broken (since I did not port these to Vue 3).

**Comment by danielgarthur** [comment]
I found this: https://github.com/mauricius/vue-draggable-resizable/issues/273#issuecomment-915237515

**Comment by danielgarthur** [comment]
And this: https://github.com/ckpack/vue-color

**Comment by basil** [comment]
Nice! I pushed basil@8b48a7c1fdc1e4f57b570047da69e1395bfd224e, which gets the color picker and image resizing working based on those comments. I also pushed basil@53b25b63365c2e239c182a85bc2d73c58b776ea3 which fixes some `v-model` bugs. As of that commit, scrolling is still broken. I also noticed that playback is broken. At the moment, those are the only two problems I know of.

**Comment by basil** [comment]
I fixed the playback in basil@ec9f0cd5626359da5d18b7e1f872ff760ff3e65f. Vue 3 was treating this as a reactive property, which was interfering with the Tone.js framework. I fixed that by using the Vue 3 provide/inject API to register the audio service and playback service as singleton services.

The only issue I am still having on this branch is that scrolling is broken. After spending a lot of time stepping through the guts of Vue rendering internals, I still have no idea why.

**Comment by danielgarthur** [comment]
I've pulled down your latest commit and scrolling seems to be working on Windows. I've haven't tried on Linux or Mac, yet. Is it that the scroll bar doesn't appear for you? Or does it scroll, but the later pages never load?

**Comment by danielgarthur** [comment]
I found the issue. In Vue 3, `app.mount('#app')` no longer replaces the div. See on the right (Vue 3), there are now two layers of div with the `id="app"`. This extra layer messes up all the styling below that layer.

<img width="796" alt="image" src="https://github.com/danielgarthur/neanes/assets/4132779/428f5615-7538-471f-a295-37f5020497f9">

Reference in the migration guide is [here](https://v3-migration.vuejs.org/breaking-changes/mount-changes.html). It looks like we can either set a compiler flag to change this behavior, or we could 

1. Update eslint config to use Vue 3 (needed anyway, and this will result in a bunch of warnings)
2. Remove the outer div in `App.vue`
3. Move the styling for `#app` from the scoped styling block into the global styling block (in `App.vue`)

**Comment by basil** [comment]
There we go! Now we're cooking with gas.

> I made the above changes and I can scroll through my multi-page files.

I was not able to replicate your changes on my branch. Are you interested in collaborating on a shared branch?

**Comment by danielgarthur** [comment]
Yes, what would be the best way to do that? I think with a PR you can allow me to make changes to the branch, but I am not all that familiar with Github collaboration patterns.

**Comment by basil** [comment]
⇨ #142
