### ISSUE TITLE
[BUG] Apostrofos syndesmos with gorgon (gorgonAbove) on first apostrofos

### ISSUE THREAD

**Issue by ilizol** [danielgarthur/neanes#14]
**This bug was found in**
- [ ] Desktop
- [ ] Web App
- [x] Both 

**Describe the bug**
Apostrofos syndesmos with gorgon (gorgonAbove) on first apostrofos.

**Expected behavior**
Apostrofos syndesmos with gorgon (gorgonAbove) on second apostrofos.

**Screenshots**
![apostrofos_syndesmos_with_gorgon](https://user-images.githubusercontent.com/7188298/179411263-bb6e3cb4-f577-41e7-8df5-eb096514359d.png)

**Desktop Version (please complete the following information, if applicable):**
 - OS: Debian 10.12
 - Version 0.2.0-alpha.15

**Web App (please complete the following information, if applicable):**
 - Browser Chromium
 - Version 90.0.4430.212

**Comment by danielgarthur** [comment]
Example for reference:

![image](https://user-images.githubusercontent.com/4132779/179440982-76d11ac5-9da1-44f1-930f-db5ca4ff78b8.png)
