### ISSUE TITLE
Word extensions cannot continue past martyriæ

### ISSUE THREAD

**Issue by basil** [danielgarthur/neanes#145]
Word extensions cannot continue past martyriæ. This is a serious problem for papadic pieces. See, for example, the First Mode Cherubic Hymn in _The Musical Ark_ by N. Roumas:

![word-extension-martyria](https://github.com/danielgarthur/neanes/assets/29850/a5354f28-551e-452d-b3b2-a7ec9ba9aa3f)

See also the Koukouzelis Koinonikon typeset by J.M. Boyer:

![jmb-koinonikon](https://github.com/danielgarthur/neanes/assets/29850/f6425eb5-2b8e-4022-9d18-f26e82ac05b9)

While the former breaks the word extension for the martyria and then resumes it after, the latter continues the word extension through the martyria. Regardless, the word extension must resume after the martyria.

**Comment by danielgarthur** [comment]
I'll fix this after the Vue 3 change is in.
