### ISSUE TITLE
[BUG] macOS—Two windows open when I open a byz or byzx file

### ISSUE THREAD

**Issue by PsaltyDog** [danielgarthur/neanes#147]
**This bug was found in**

- [x] Desktop

**Describe the bug**

So, running macOS, if I run Neanes from the Dock, it opens fine, one window. 

However, if I open a byz or a byzx file from Finder, with the program not yet running, then it opens two identical windows with the same file displayed. 

If the program is already running when I open the byz or byzx file from Finder, then there's no problem, one window.

**Desktop Version (please complete the following information, if applicable):**

- OS: macOS 13.4.1
- Version 0.3.0-beta.20

**Comment by t-bullock** [comment]
I see this behavior as well in version 0.4.1.

**Comment by danielgarthur** [comment]
I haven't been able to reproduce it on macOS 12.6.7. But the computer I am testing on is pretty powerful and I wonder if there is some race condition that shows up only when Neanes takes longer to load.

How long does it take Neanes to load for you?

**Comment by PsaltyDog** [comment]
> How long does it take Neanes to load for you?

Between 3 and 4 seconds. This is on a 2022 MacBook Pro running Ventura 13.4.1

**Comment by t-bullock** [comment]
I'm also on MacOS 12.6 and the program opens in 2 seconds or lesser.

**Comment by danielgarthur** [comment]
I've attempted to fix this in [0.4.2](https://github.com/danielgarthur/neanes/releases/tag/v0.4.2). But I wasn't able to reproduce it, so I'm not sure whether I was successful.

I added more checks around every piece of code that creates a window, in an attempt to prevent more than one window from being created.

**Comment by t-bullock** [comment]
> I've attempted to fix this in [0.4.2](https://github.com/danielgarthur/neanes/releases/tag/v0.4.2). But I wasn't able to reproduce it, so I'm not sure whether I was successful.
> 
> I added more checks around every piece of code that creates a window, in an attempt to prevent more than one window from being created.

Seems to be fixed for me. Thank you!
