### ISSUE TITLE
[BUG] Unable to open files saved with foriegn characters in the name

### ISSUE THREAD

**Issue by JoelSDavies** [danielgarthur/neanes#16]
**This bug was found in**
- [ ] Desktop
- [ ] Web Ap
- [x] Both 

**Describe the bug**
When you save a file and name it in Greek (or use other foreign characters such as ë), Neanes will not open the file again. With the desktop version, you will just get a strange error message, such as "invalid distance too far back", "invalid code lengths set", or "invalid block type". The web version does not show such messages but just fails to open the file. Renaming the file to have only English characters does not fix the problem.

**To Reproduce**
1. Create a new score
2. Save it as "Ὁ οὐρανὸν τοῖς ἄστροις" (or anything else in Greek)
3. Try to open the saved file

**Expected behavior**
Should be able to open any files saved out of Neanes, regardless of the filename.

**Desktop Version (please complete the following information, if applicable):**
 - OS: Windows 10 (21H2)
 - Version 0.2.0-alpha.15

**Web App (please complete the following information, if applicable):**
 - Browser Chrome
 - Version 103.0.5060.114

**Comment by danielgarthur** [comment]
Seems related to https://github.com/cthackers/adm-zip/issues/422.

I've switched to jszip, which seems to work fine.
