### ISSUE TITLE
Allow gorgon to be placed below oligon when combined with kentema or ypsele

### ISSUE THREAD

**Issue by basil** [danielgarthur/neanes#170]
See the circled portions of this Axion Estin in Greek by Michael Hatziathanasiou. If a gorgon is attached to a plain oligon, Neanes allows you to place the gorgon either below or above the oligon (correctly). But when the oligon also has a kentema or an ypsele, as in the circled portions of the score, Neanes only allows you to place the gorgon above the oligon (incorrectly). Neanes should allow the gorgon to be placed either above or below the oligon, as the presence of a kentema or an ypsele makes no difference here. Generally, the gorgon should be placed below the oligon (as it is in the circled portions of this score) unless there is a specific reason to place the gorgon above the oligon, such as the presence of an antikenoma below the oligon — in such a case, the antikenoma cannot go above the oligon, and once the antikenoma is below the oligon there is no more space for the gorgon so the gorgon has to go above the oligon. But in the majority of cases the gorgon should go below the oligon. Note that this score contains orthographical errors, but the portions I circled are correct. Neanes should allow the gorgon to be placed above or below the oligon in all of these cases.

![AxionEstin_X''Athanasiou_PLD](https://github.com/danielgarthur/neanes/assets/29850/e72c2da4-e9b2-4196-ae6f-00cb606bb62f)

**Comment by basil** [comment]
An even better example of this being a completely valid thing to do: see the circled portion of this score by (the orthographically impeccable) George Sarantaekklisiotou.

![Sarantaekklisiotou](https://github.com/danielgarthur/neanes/assets/29850/0bbef629-a47e-4668-9910-80c81cd65691)

**Comment by danielgarthur** [comment]
This limitation was based off of Rule 50 from Fr Ephraim's compilation, but I agree that it appears often enough that users should not be restricted from using this. 

In general, I am in favor of allowing more freedom and implementing a "spell checker" where users can turn on and off rules like in eslint.

**Comment by basil** [comment]
He writes that rule 50 was "surmised from personal observations", and I think his personal observations were simply a bit off in this case, as these examples show. I think he should have written "usually placed above compound symbols" rather than "always placed above compound symbols" in that rule.

**Comment by danielgarthur** [comment]
Ah, I never noticed that footnote. I agree that it should be allowed. I'll need to update the font since I am pretty sure the lower gorgon anchors are missing altogether from the mark to base tables.

**Comment by basil** [comment]
BTW in both http://music.samonastery.org/Chrys/b0670_It%20is%20truly%20right-Hatziathanasiou.pdf and http://music.samonastery.org/Chrys/b0750_Mode%205%20Hatziathanasiou.pdf Papa Ephraim corrected Hatziathanasiou's orthographical errors (and there are many!), but yet in both of those scores Papa Ephraim left the gorgon below any compound neumes (unless there was an antikenoma already below the oligon).

**Comment by basil** [comment]
In [ΜΠΤ 703](https://analogion.com/psaltologion/703%20p361-400.pdf) Chourmouzios writes a gorgon below an oligon with kentema on page 393, so I think we can safely conclude Papa Ephraim was wrong about this.

![Screenshot_20230716_011246](https://github.com/danielgarthur/neanes/assets/29850/59bf8719-fc17-49ef-8381-79e45a4a7241)
