### ISSUE TITLE
Neanes sometimes eats fthoras

### ISSUE THREAD

**Issue by basil** [danielgarthur/neanes#174]
First of all, let it be said that I love this program and am extremely grateful for it. As Steve Jobs once said, it is like a bicycle for the mind. I have already composed 20 pieces in it, and I plan to write more this weekend. I love being able to iteratively revise and polish compositions, which was prohibitively difficult when writing out scores by hand or using word processing software.

After spending many hours in the program, my two biggest annoyances so far are the barline support (chronicled in other tickets) which requires frequent and tedious manual positioning—I am starting to memorize various offsets due to personal deficiencies—and its tendency to eat fthoras.

Yes, I thought I was going crazy at first. But this program does eat fthoras. This isn't so much of a problem if you enter a completed score from start to finish, but it is a problem if—like me—you compose by iteratively revising and polishing. Try, for example, opening https://github.com/basil/byzantine-music/blob/master/Divine%20Liturgy/Leitourgika%20and%20Axion%20Estin/Axion%20Estin%203.byzx and note that the first Zo on page 2 has an ajem. Now do something on page 1, like deleting any oligon. You might do this, for example, when changing the melody for a certain phrase. After deleting the oligon, the entire piece from that point forward is (temporarily) off by one, and the ajem on page 2 has disappeared because that note is now (temporarily) a Ke rather than a Zo (and an ajem makes no sense on a Ke). But now go to the Edit menu and select Undo to restore the oligon that was deleted. The score is no longer off by one, but the ajem is still missing from the first Zo on page 2. I would have expected the undo to leave the score in the same state it was in previously.

This has a practical impact, as making even simple edits to the beginning of a piece has destroyed some of the fthoras that I spent a lot of time (and careful modal reasoning) putting into place, often without me realizing it until much later. I've now gotten to the point where I don't trust the program anymore, so I save frequently (using Git to track my changes and `git add -p` to review every modification) just in case it decides to eat my fthoras again.

**Comment by danielgarthur** [comment]
The code that eats the fthores was written before the command history service was in place, and so it doesn't go through the "proper channels", so to speak. It never notifies the history service about what it's doing. There are similar issues with certain characters of quality that are changed outside the proper channels. I will fix this.

To reduce frustration in the meantime, you can go to Page Setup and check `Disable Fthora Restrictions`. If this is checked, then even if you change previous notes, it will always keep the fthora and never remove it, regardless of the note value.

Or perhaps this latter behavior should simply happen all the time? What is your opinion? Should Neanes ever remove fthores? Users can always manually remove the fthora if they no longer want it there, which is probably the less likely case, compared to users wanting to alter previous neumes and keep the fthora.

**Comment by basil** [comment]
Thanks for telling me about the **Disable Fthora Restrictions** workaround. I think that will reduce my frustration in the short term.

I think it does make sense to disallow invalid states by default, including removing invalid fthoras. My general view is that it is good for software to be at least a little opinionated if that results in a simpler user experience, compared to the software being unopinionated but having a more complex user experience. However, if software is too opinionated, then people simply won't use it. Jenkins is relatively unopinionated, and while people don't necessarily love it, they still use it.

The problem from my point of view is not that the fthora is being removed when we enter an invalid state; rather, the problem is that the fthora is not being restored when we reënter a valid state. To that end, it makes sense to me that the program should maintain a history of sorts in memory (persisting this to disk seems like it would be surprising/problematic) so that automatic changes can be undone when a valid state is reëstablished.

It is not just undo/redo that can result in the reëstablishment of valid state. For example, deleting an oligon can make everything from that point forward off by one, creating an invalid state, and then a valid state can be restored by adding a petaste, all without invoking undo/redo.

**Comment by PsaltyDog** [comment]
What about making it so that the default setting disallows the entry of invalid states, but allows them to persist if they result from a change in another part of the score?

**Comment by basil** [comment]
My initial reaction is it seems inconsistent that the program would allow an invalid state to be achieved indirectly (by creating A' and then editing it to A) but not directly (by entering A directly). The simplest and most consistent approach to invalid state is to not allow it to be representable at any given time.
