### ISSUE TITLE
Draggable tabs

### ISSUE THREAD

**Issue by basil** [danielgarthur/neanes#180]
I would very much like to drag and reorder tabs, as in the "after slots" example [here](https://viewweiwu.github.io/vue3-tabs-chrome/). Unfortunately, after trying for several hours I was not able to implement this. I just can't figure out how to convert the example usage in the `vue3-tabs-chrome` README from the Composition API to the Options API, let alone `vue-facing-decorator`. All my attempts seemed to have subtle reactivity problems, such as new tabs being added to the tabs object but not being actually rendered in the browser. My code is most likely too embarrassing to look at. The example uses both `refs` and `reactive`, for reasons that are not clear to me, but I can't seem to find a way to express the same distinction in the Options API.

On top of that, I would very much like to be able to right-click on any tab and select "Close", "Close others", "Close to the left", and "Close to the right", but since I failed so spectacularly in the first task I did not even attempt implementing this.

**Comment by danielgarthur** [comment]
That plugin's interface was unlike most Vue components I've seen, but I was able to get it to work.

`vue-facing-decorator` obscures away the differences between `ref` and `reactive` and in general you shouldn't need to worry about it. In the code example, there is no particular need to use `reactive`, it was probably just personal preference by the author, motivated perhaps by the fact that the array was never going to be reassigned and it eliminates the need to write `.value` to access the array.

**Comment by basil** [comment]
Thank you very much! This has drastically improved the usability of the program for me. I compared your code to my failed attempt, and I had about a third of it right and two thirds wrong. Hopefully in the future that percentage will increase.
