### ISSUE TITLE
Headers/footers do not re-render after changing formatting options

### ISSUE THREAD

**Issue by basil** [danielgarthur/neanes#206]
Perhaps some collateral damage lingering from the Vue 3 upgrade: after clicking bold/italic on a header/footer and then clicking on a neume, the text box does not re-render with bold/italic. It does re-render after I switch tabs and switch back to the workspace though.

**Comment by danielgarthur** [comment]
I'm having trouble reproducing this one. If you create a new score, click on the "Title" text box, then press the bold button, are you saying it doesn't turn bold for you immediately?

**Comment by basil** [comment]
Sorry, my bad. I meant "header/footer", not "text box." Text boxes do indeed work fine.
