### ISSUE TITLE
Enharmonic fthora

### ISSUE THREAD

**Issue by gugushvili** [danielgarthur/neanes#215]
Not that it's critical, but Neanes doesn't seem to allow me to use the enharmonic fthora in theseis like διὸ τὴν πανύμνητον here in the heirmos of the 9th Ode of the Resurrectional canon (Second mode):

https://youtu.be/3u5ZMIQPaBU?t=317

What confuses it is that Vou is taken as Pa.

**Comment by danielgarthur** [comment]
For this, you can check Disable Fthora Restrictions in the Page Setup dialog. This allows fthores to be placed anywhere, although you may need to manually change martyria in some cases.

**Comment by gugushvili** [comment]
That's a workable solution. I'll close the issue for now.
