### ISSUE TITLE
[ENHANCEMENT] Ajem fthora position

### ISSUE THREAD

**Issue by gugushvili** [danielgarthur/neanes#218]
Positioning of the ajem fthora is inconsistent: when a 3-voice ascent is with petaste, it goes on top and is in the centre. Otherwise, with oligon, it's shifted to the right. The first option looks ugly. I suggest the ajem fthora goes by default to the right in such cases.

<img width="676" alt="Screenshot 2023-08-14 at 15 23 38" src="https://github.com/danielgarthur/neanes/assets/37747348/af66e851-8e0e-4154-94e2-82d9b0fcc21e">

**Comment by danielgarthur** [comment]
Added to release `0.4.3`.
