### ISSUE TITLE
[BUG] When a neume has both a syndesmos and dipli/tripli, they overlap

### ISSUE THREAD

**Issue by JoelSDavies** [danielgarthur/neanes#22]
**This bug was found in**
- [x] Desktop
- [x] Web App
- [x] Both 

**Describe the bug**
When a neume has both a syndesmos and dipli/tripli, they overlap. There is a fairly common pattern where an neume (normally ison/oligon/apostrophos) has a vareia, dipli/tripli, and syndesmos connecting it with an apostrophos with a gorgon. For a couple examples off the top of my head, see Πανδέκτη τ. β΄ (Όρθρος) - Την τιμιωτέραν πλ. δ' (pg 508 in the PDF I have), or [Fr. Ephraim's orthography rules](https://music.samonastery.org/ByzOrthography.pdf) #72 

**To Reproduce**
1. Type a neume
2. Add dipli
3. Add syndesmos
4. Characters overlap

**Expected behavior**
Syndesmos should not overlap the dipli/tripli. See examples mentioned above for ways that it could look. Usually syndesmos is lowered in this case. Sometimes it is angled. Some books also make the dipli/tripli smaller (but I don't prefer that because that makes them hard to see.

**Screenshots**
![image](https://user-images.githubusercontent.com/109194732/195767260-c1059f0f-c431-4a09-b347-2ec57befdbbd.png)

**Desktop Version (please complete the following information, if applicable):**
 - OS: Windows 10
 - Version 0.2.0-alpha.25

**Web App (please complete the following information, if applicable):**
Note: That the web app version currently only supports Chromium-based browsers. Mobile devices are not currently supported. Please do not file a bug if not using an unsupported browser or a mobile device.
 - Browser Chrome
 - Version 0.2.0-alpha.25

**Comment by danielgarthur** [comment]
I've added a dialog to allow users to position each supporting neume. See the docs [here](https://danielgarthur.github.io/neanes/guide/advanced.html#fine-tuning-neume-positions).
