### ISSUE TITLE
Martyria calculation bug

### ISSUE THREAD

**Issue by basil** [danielgarthur/neanes#248]
Both of these examples play back correctly, but the second one has an incorrect martyria:

![Martyria calculation-1](https://github.com/danielgarthur/neanes/assets/29850/68134e92-7330-4f7b-817f-9cbe1a1e41c4)

If nobody beats me to it, I will try to debug this and file a PR later this week.

**Comment by danielgarthur** [comment]
This is probably related to the TODO [here](https://github.com/danielgarthur/neanes/blob/master/src/services/LayoutService.ts#L1511). I think it breaks for any multi-note neume group.

**Comment by basil** [comment]
As of recent commits this is fixed in both layout and playback.
