### ISSUE TITLE
[BUG] No syndesmos-psifiston combination

### ISSUE THREAD

**Issue by PsaltyDog** [danielgarthur/neanes#26]
**This bug was found in**
- [x] Desktop
- [ ] Web App
- [ ] Both 

**Describe the bug**
There is no syndesmos-psifiston combination, so what should display as:

![Ex1](https://user-images.githubusercontent.com/116736628/198063046-0373babb-fb0d-4e88-a966-74799ad97fa6.png)

instead displays like this:

![Ex2](https://user-images.githubusercontent.com/116736628/198063125-3605b081-b6ee-4ee5-ad54-b13b3627f3a7.png)

**Comment by danielgarthur** [comment]
These neumes have been added and can be accessed by either using the click-and-hold menus for the connecting heteron and the psifiston, or by using <kbd>Shift</kbd> + <kbd>V</kbd> + <kbd>M</kbd> for the heteron, and <kbd>Shift</kbd> + <kbd>V</kbd> + <kbd>K</kbd> for the psifiston.
