### ISSUE TITLE
Playback bug

### ISSUE THREAD

**Issue by basil** [danielgarthur/neanes#261]
Trying to sift through the various issues in playing back verse 1 of Makarios Anhr, I whittled down one issue into this minimal reproducible example:

![playback1-1](https://github.com/danielgarthur/neanes/assets/29850/c2019181-290d-44fb-9f83-3ef51b9bbf03)

This example does not have any fthoras on compound neume groups, so the problem is more fundamental than compound neume complexity. Once you hit the second fthora, the playback goes off the rails even though the ison still remains correct, resulting in a final note that does not match the ison.

**Comment by danielgarthur** [comment]
My guess, just from looking at the image, is that when going up to the vou marked diatonic, the playback probably only goes up to vou from the hard chromatic scale, resulting in a flat melody.

If you instead put a pa fthora on the pa before vou, does it play back correctly?

**Comment by basil** [comment]
This is the most severe bug I am aware of in the playback system. While it happens more frequently in analytical scores, such as the anonymous Pl 2nd "It is truly meet" in _Mousikos Thisavros_, it also happens in some classical scores like the "Blessed is the man" by both Peter the Lampadarios and Manuel the Protopsaltis. In practice I have only seen a problem when a diatonic fthora is placed on a previously hard chromatic neume.

**Comment by danielgarthur** [comment]
I've seen it also when a second mode melody hard-chromatically descends to Ni, and then returns to soft chromatic on Vou.
<img width="95" alt="image" src="https://github.com/danielgarthur/neanes/assets/4132779/93567052-30e4-4506-b80e-69d3b815f9c4">

My initial thought is that when a fthora is encountered, instead of using `moveDistance` and moving relatively based on the current scale, we should instead jump to the absolute frequency of Vou, which can be calculated based on Di and the target scale determined by the fthora. Does this sound right?

**Comment by basil** [comment]
That would work, yes. Another way of thinking about this is to calculate the pitch of the note with the fthora relative to some pivot point, a "[phase change](https://en.wikipedia.org/wiki/Phase_transition)" note that is the same pitch in both scales. In https://github.com/danielgarthur/neanes/issues/261#issue-1874144744 the first fthora's pivot point is the note with the fthora itself (Pa which is the same pitch in the original scale and the target), while the second fthora's pivot point is the preceding note (as you observed in https://github.com/danielgarthur/neanes/issues/261#issuecomment-1699751443, Pa which is the same pitch in the original scale and the target scale). In https://github.com/danielgarthur/neanes/issues/261#issuecomment-1702023985 the fthora's pivot point is the preceding note (Ni which is the same pitch in the original scale and the target scale). So once a pivot point (which could be thought of as being in both scales at once, like a melting object can be thought of as being both solid and liquid at once) is selected, the next note after the pivot point transforms fully into the new scale. If the note with the fthora isn't the pivot point, the preceding note could be the pivot point. But in some very rare cases neither the note with the fthora nor the preceding note are pivot points…

Where this "pivot point" idea breaks down is when there is a pitch upheaval, such as on line 2 of https://www.youtube.com/watch?v=HMtWzcBEWwg where the melody moves up from Diatonic Ni (Physical Ni) to Diatonic Ni (Physical Pa) for a line or so, before returning to the original Diatonic Ni (Physical Ni). And in extreme cases like [Τω Τριττώ της Ερωτήσεως](https://analogion.com/site/html/TwTrittw.html) there is a pitch upheaval that lasts for the entire rest of the piece such that the piece finishes higher than it started (!). You generally only find these pitch upheavals in very old pieces, like the ancient compositions by Koukouzelis, the Old Sticherarion, etc. While this phenomenon is certainly legitimate, it is encountered extremely rarely in modern psaltic practice so I think it would be perfectly reasonable to punt on it for now in favor of prioritizing the common examples I described in the previous paragraph.

**Comment by basil** [comment]
> You generally only find these pitch upheavals in very old pieces, like the ancient compositions by Koukouzelis, the Old Sticherarion, etc.

Well there and also in some compositions of Raidestinos, Pringos, and Stanitsas. My point is that it's legitimate but not nearly as high of a priority as what I described in the first paragraph.

**Comment by gugushvili** [comment]
I was wondering what the playback rules are when a piece terminates without a fthora being released and one moves on to the next piece. Example: enharmonic fthora on high Zo in the Kekragarion of the First Mode. It is repeated in both "Lord I have cried" and "Let my prayer", while in the stichology Zo flats are explicitly notated. This suggests that the fthora effect terminates with the end of the piece and the martyria giving the basis of the next pieces indicates a fresh start.

**Comment by basil** [comment]
> Until very recently, the ajem fthora was terminated at the first martyria after the fthora.

Am I missing some recent commit? As of commit 2397b33 the ajem is still (incorrectly) terminated at the first martyria after the fthora, from a playback perspective:

![ajem-bug](https://github.com/danielgarthur/neanes/assets/29850/243aae77-fa61-4c64-9431-ebc0974e3f12)

This has long annoyed me, but I have not filed a ticket for it because (comparatively speaking) it is a minor issue compared to the other tickets I have filed. Additionally, sometimes the ajem is used more like a flat sign, which is arguably a deficiency of the score itself. I seem to remember reading some source about this but I can't remember it now. Still, it probably makes sense for an ajem to be permanent from a playback perspective. However there are far more pressing playback issues.

**Comment by basil** [comment]
> My initial thought is that when a fthora is encountered, instead of using `moveDistance` and moving relatively based on the current scale, we should instead jump to the absolute frequency of Vou, which can be calculated based on Di and the target scale determined by the fthora. Does this sound right?

@danielgarthur I've implemented this in my "playback rewrite" branch (sorry, code is too messy to share right now, but I am getting closer and closer to finishing it and posting a PR), and it fixes a huge number of playback issues across all of my Axion Estins. I had to develop this idea a bit further for it to be practical:

- For Spathi, calculating the interval based on Di and the target scale determined by the fthora doesn't work because Di isn't stable relative to the Di frequency configured in the playback options. I've hacked around this by special-casing Spathi and doing the calculation relative to Ga or Ke, then incrementing or decrementing by 12 moria to adjust the result to be relative to be Di. I'm open to better solutions here, but this is working pretty well in practice for my two Axion Estins in Hisâr-Bûselik.
- When a fthora is in effect, you need to adjust the result by the number of moria of the transposition (what you call the "shift" in some parts of the code). Computing this isn't trivial. You can't take the number of moria from the physical note to the virtual (transposed) note in the old scale, because that doesn't work when jumping from Diatonic Pa to Enharmonic Zo. You can't take the number of moria from the physical note to the virtual note in the new scale either, because that doesn't work when jumping from Soft Chromatic Di to Diatonic Pa' (with a low Pa Diatonic fthora). The compromise I settled on, which works a lot of the time, is to compute the distance from the physical note to Di in the old scale, then compute the distance from Di to the virtual note in the new scale, then sum the two. This works whenever the two scales are aligned on Di; however...
- The above solution breaks down if, say, you are in Diatonic Ni and put a Hard Chromatic fthora on Vou, thus creating a tonal upheaval. The same occurs in the Anoixantaria by Koukouzelis (abbreviated by Chourmouzios) and the end of To tritto tis erotiseos. In these cases, computing the moria of the transposition as described above breaks down, because the original scale and the target scale aren't aligned on Di. As a result the computation is off by an arbitrary amount since the scales don't align with each other, at least not at the point the algorithm is expecting them to. Conceptually, the scales do align, but just not on Di in both scales: in the case of a Hard Chromatic fthora on Diatonic Vou, they align based on physical Zo/virtual Ke, which is intuitive to me as a human but not to the computer. I can't figure out a heuristic to determine this in code.

I will keep thinking about this, but I would appreciate some help coming up with an algorithm for this problem. I realize it will be a lot easier to work on this once I share my code, and I am probably going to be ready to do that in a week or so, but I have to clean up a bunch of stuff first. I will say that I have played back all my Axion Estins with my new code today, and (besides the above issue) they are playing back far better than with the existing code. And this has been invaluable for me as I prepare the work for final publication, because I have found many minor editorial issues by playing back the work in a (functioning) software program.

**Comment by basil** [comment]
⇨ #322

**Comment by basil** [comment]
> Example: enharmonic fthora on high Zo in the Kekragarion of the First Mode. It is repeated in both "Lord I have cried" and "Let my prayer", while in the stichology Zo flats are explicitly notated. This suggests that the fthora effect terminates with the end of the piece and the martyria giving the basis of the next pieces indicates a fresh start.

Can you please show more examples of this. It is difficult to draw general conclusions from a single example.

**Comment by basil** [comment]
Since the originally reported issue is now fixed, I am closing this issue. Please file a separate issue regarding the fthora termination issues, with more examples as requested.
