### ISSUE TITLE
Refactor `LayoutService` and `PlaybackService`

### ISSUE THREAD

**Issue by basil** [danielgarthur/neanes#294]
Both `LayoutService` and `PlaybackService` contain duplicate logic for interpreting neumes: expanding combinations into note atoms, determining the current note for the purposes of martyria and ambitus calculation, etc. I think it might be easier to fix the remaining bugs in the `PlaybackService` if this logic were first refactored and simplified. What I had in mind was a new `AnalysisService` whose purpose is to take in a list of `ScoreElement`s and output an intermediary representation (like bytecode) of the analyzed score without mutating the original `ScoreElement`s. This intermediate representation would contain everything needed to efficiently do layout and playback, without getting into the lower-level details. For example, the intermediate representation would contain things like note atoms (decomposed compound neumes) with relative beat durations, current scale, current physical note, current virtual note (if a fthora is in effect), etc. `LayoutService` would take this return value and use it to calculate each martyria, ambitus, note indicator neume, etc. `PlaybackService` would take this return value and generate playback events based on user preferences. It would be easy to debug a playback problem by setting a breakpoint on the return value of `AnalysisService` and verifying that the neumes were correctly analyzed, and this should be easier than debugging today because there would be a greater separation of concerns between each service. `PlaybackService` would just be executing the intermediate representation in the same way the JVM executes bytecode. Neither `LayoutService` nor `PlaybackService` would be in the business of interpreting neumes. Thoughts?

**Comment by basil** [comment]
I started working on this and have implemented bytecode generation for all layout events and most playback events (except fthoras), including gorgon calculation, as well as porting the layout service to consume the bytecode seemingly without regression. Tomorrow I will try to port the playback service to consume the bytecode and see if I can get a score without fthoras to play back correctly, then work on the fthora bytecode on both the producer and consumer side. So far the bytecode looks very similar to the format used by [music trackers](https://en.wikipedia.org/wiki/Music_tracker). Debugging the intermediate representation is so much easier than debugging the existing playbacks service, and I've already fixed several pet bugs after logging the bytecode for some of my existing scores. I'm hopeful that the end result will be simpler and easier to maintain.

**Comment by basil** [comment]
I hacked on this a little more this evening and reached the point where `AnalysisService` emits all events needed for layout and all events needed for playback (except fthora-related events), `LayoutService` consumes these events to do layout (seemingly without regression) and `PlaybackService` consumes these events to do playback (seemingly without regression, except for lack of fthora support). I'm pleased with the results so far: a net deletion in lines of code and the relevant services are much easier to understand with a tighter separation of concerns. Next I plan to define the interface for scale/fthora changes and try to implement fthora support in this new model. The goal would be to fix the remaining playback issues, taking advantage of this improved design.

**Comment by danielgarthur** [comment]
This all makes sense to me and it sounds like a good direction.

**Comment by basil** [comment]
I hacked on this a little more and have almost all existing functionality (except for disable fthora restrictions, fthora carries, and some other odds and ends) working in the refactored version. The new version is about 400 lines of code shorter than the original, and much simpler/clearer I think. This weekend I will try to clean up the code and fix some actual bugs. My goal is to get all of my Axion Estin settings to play back correctly, and I am aware of several bugs ranging from minor to severe.

**Comment by basil** [comment]
I hacked on this a little more today and fixed a bunch of existing bugs. The software can now play the first few verses of Makarios Anhr correctly as well as my Axion Estin in Maqam Hümâyûn which previously had a lot of bugs. Lots of minor issues in my Axion Estins are fixed. Many issues are fixed in the first verse of Koukouzelis' Anoixantaria (as abbreviated by Chourmouzios), which now plays back almost correctly modulo a two moria error due to lack of support for mode upheavals. There are still some bugs in my maqam-focused Axion Estins, some pre-existing and some new, as well as a regression in enharmonic grave mode that I haven't tracked down yet. This code still needs a lot of work, but I'm hopeful that eventually I can get playback to a fully functioning state.

**Comment by basil** [comment]
Pitch upheavals, as occur in Koukouzelis' Anoixantaria and To tritto tis erotiseos, continue to be a problem. I still haven't figured out a way to detect them or to compensate for them.

**Comment by basil** [comment]
I worked on this a little more today and fixed about half of the remaining minor bugs. Unfortunately, I have not made any progress on the remaining major bug: figuring out a way to calculate pitch upheavals correctly.

**Comment by basil** [comment]
Fixed in #322
