### ISSUE TITLE
Default position of lower tie is too low

### ISSUE THREAD

**Issue by basil** [danielgarthur/neanes#330]
The tie that goes beneath neumes (rather than above) them has a default position that is too low and collides with lyrics 90% of the time, requiring manual adjustment. A default position that is just slightly higher would look better and require less frequent manual adjustment.

![tie-below](https://github.com/danielgarthur/neanes/assets/29850/013f2f9f-d76e-417c-99de-243985a4453f)

**Comment by basil** [comment]
Let me know if we actually want to do this, and I can easily change the y-coordinate in the font.

**Comment by danielgarthur** [comment]
I'm good with moving it up.
