### ISSUE TITLE
[ENHANCEMENT] Stavros between running elafron

### ISSUE THREAD

**Issue by LeSniffa** [danielgarthur/neanes#338]
Is there a way to place a stavros between the two neumes of the running elafron?
![image](https://github.com/danielgarthur/neanes/assets/110656129/ed6001e0-4ca5-409f-9773-a7ab64d09df4)

**Comment by danielgarthur** [comment]
No, there is not, but this could be added. Is the running elafron the only combination that can take a stavros?

**Comment by LeSniffa** [comment]
Yes as far as I know.

**Comment by danielgarthur** [comment]
Added to [v0.4.9](https://github.com/danielgarthur/neanes/releases/tag/v0.4.9).
