### ISSUE TITLE
[ENHANCEMENT] Justifying line break

### ISSUE THREAD

**Issue by PsaltyDog** [danielgarthur/neanes#39]
Would it be possible to have, in addition to the regular line break, a line break that also justifies the line you've broken? It would make it easier sometimes when phrases are broken in an awkward spot.

**Comment by danielgarthur** [comment]
@PsaltyDog I'm not sure I understand what you are asking for. Could you please share a screenshot that illustrates the behavior that is happening now that you don't want and describe how it should change? 

I think what I'm not clear on is what the broken line should be justified against. That is, non-broken lines are justified against the right side of the page. What should broken lines be justified against?

**Comment by PsaltyDog** [comment]
Sorry, I was wondering even as I wrote that if I was being clear or not.

So, it's really a completely cosmetic thing: sometimes a combination that looks odd broken over a line break occurs nonetheless over a line break, for example a syndesmos:
![evil problem1](https://user-images.githubusercontent.com/116736628/208538869-fae2c1eb-5926-4774-9d99-c58306a8deab.jpg)
If I use a line break to break it in a different place, it doesn't justify the line to the right side of the page, and so it looks like a break in the music:
![evil problem2](https://user-images.githubusercontent.com/116736628/208539017-97df2b7a-05cb-44cb-9ffc-5235b232bb35.jpg)
So instead, I end up manually adjusting the spacing for each individual neume to make a new line break (it would also be nice to be able to adjust the spacing of more than one neume at once):
![evil problem3](https://user-images.githubusercontent.com/116736628/208539192-2e97657e-9059-448d-a7ea-7e8fa55501a4.jpg)
If there were an option to create a line break which would justify the line to the right side of the page, like there's no break in the music, this could be done in a click of the mouse.

Thank you for all your work on this program, and forgive me for bothering you with something so cosmetic. :)

**Comment by danielgarthur** [comment]
I understand now. I can look into it. 

I think another improvement could be to keep characters together when they are linked by a quality character. That is, automatically move the characters to the next line when the heteron is added, for example. Something like this happens with martyria already, where martyria are "tied" to the previous quantity character and may force the linked character onto the next line.

**Comment by danielgarthur** [comment]
@PsaltyDog I've made the change to keep tied notes together (i.e. notes connected by a syndesmos or an omalon).

Is there any other situation where you would want to break a line early and justify?

I could see how maybe one might want to break a line early to avoid a melisma across two lines. But I wanted to check first if you've run into anything besides tied notes.

**Comment by PsaltyDog** [comment]
Thank you! This was the only case that looked really ugly to me.

There are a number of melismas I've noticed that would be nice to have the option to keep together; for instance:

1) any neume with antikenoma and apli followed by apostrophos-gorgon; 
2) basically any neume with a vareia that gets split from the neume following; or
3) a neume followed by kentimata.

![evil line breaks](https://user-images.githubusercontent.com/116736628/209103275-a2e39a61-d15e-410d-ab8a-a9117467aa1c.jpg)

But I'm not sure that I would always want to keep these together, because there may be cases where the added space looks more odd than the split. To me, these are all kind of acceptable the way they print now.

**Comment by danielgarthur** [comment]
Added justified line break.

**Comment by danielgarthur** [comment]
I changed the implementation of this with the release today, so if you used a justified line break between now and yesterday, it will be reverted to a normal line break. You can add it back by pressing the button again.

**Comment by basil** [comment]
Note that this is merely a workaround for #90.
