### ISSUE TITLE
[ENHANCEMENT] Audio Playback

### ISSUE THREAD

**Issue by efraimkaov** [danielgarthur/neanes#41]
Finally a good open source program for writing Byzantine notation.
I discovered this program today and I want to ask you if you are intending to add the option to play the Byzantine notation like Melodos does?
Thank you for your wonderful work, well done.

**Comment by efraimkaov** [comment]
I tried to use Tone.js, I managed to generate frequencies like 440, but I wasn't able to generate frequencies like 440.45, so I did it by another method
I'm still at the beginning, but you can see my code from [byz-player](https://github.com/efraimkaov/byz-player)

**Comment by danielgarthur** [comment]
@efraimkaov I put together [this](https://github.com/danielgarthur/neanes/blob/audio/src/services/audio/AudioService.ts) over the past few days using Tone.js. It's still a work in progress. 

I did not have any trouble playing the frequencies needed for Byzantine Chant. I did, however, have trouble with starting and stopping synths with the transport. I found a related [issue](https://github.com/Tonejs/Tone.js/issues/924) in Tone.js's Github issue tracker and determined that it's best to use the latest version of Tone.js via `npm install tone@next` instead of the currently released version. The `next` version seems to have some bug fixes.

**Comment by efraimkaov** [comment]
I looked at **AudioService.ts** and noticed that you put a lot of effort into writing the code.
I managed to run the development server for **neanes-master** but not for **neanes-audio**, I got this [error](https://github.com/efraimkaov/byz-player/raw/main/screenshot_2022-12-26.png). 
I have never worked with **Nodejs**, **Electron**, **Vue** or **Typescript** and I would be happy if you could guide me step by step how to solve the problem.
You are a good programmer but I'm not a programmer, I'm just a Linux guy who occasionally writes scripts in **Bash**, I also learned a little bit **Python** and a little bit **JavaScript**.
I will give up with [byz-player](https://github.com/efraimkaov/byz-player) and better help you with whatever I can with [neanes](https://github.com/danielgarthur/neanes).

**Comment by danielgarthur** [comment]
Make sure to use Node 16. [nvm](https://github.com/nvm-sh/nvm) is nice if you want to install multiple Node versions on your computer.

I'm not sure if the Node version is the issue, but it's the first thing I always check when something goes wrong.

**Comment by efraimkaov** [comment]
> Make sure to use Node 16. [nvm](https://github.com/nvm-sh/nvm) is nice if you want to install multiple Node versions on your computer.
> 
> I'm not sure if the Node version is the issue, but it's the first thing I always check when something goes wrong.

Thanks a lot, it's working, I have tried all versions of Node.js but 16
You did a very good job with Audio Playback!

**Comment by danielgarthur** [comment]
When you say it's one octave lower than the real frequency, which frequency are you expecting it to play at? Unless you've found a bug, it should be playing within the baritone range (roughly G2 - A4).

But I do plan to allow users to set the pitch of Pa, so playback could be in the soprano range if desired.

**Comment by efraimkaov** [comment]
It makes sense if is playing within the baritone range.
But I found a bug for **Hard Chromatic Scale**, **Ke Note** it should be 211.68924411671193 instead of 220
You have to calculate the **Ke Note** from **Thi Note = 195.99771799087463** which remains the same sameregardless of Scale

**Comment by danielgarthur** [comment]
211.69 is the frequency of Ke in the soft chromatic scale, where as it's 220 in the hard chromatic scale.

Di = 196 is used as the stable reference note from which the starting note is calculated.

**Comment by efraimkaov** [comment]
My bad, I was looking at something else when I calculated the frequency
So far this is what I found $\color[RGB]{0, 255, 0} GREEN$ = good frequency and $\color[RGB]{255, 0, 0} RED$ = wrong frequency
![1-1](https://user-images.githubusercontent.com/63643635/209856951-fb903b28-2b2f-4fe0-ad17-367065125055.png)
![2-1](https://user-images.githubusercontent.com/63643635/209857002-543746cc-fa22-4799-ae5e-ba11ed20f044.png)
![4-3](https://user-images.githubusercontent.com/63643635/209857024-12ab00d7-d534-49e5-9e00-f0ed13f0e4e9.png)
![6-1](https://user-images.githubusercontent.com/63643635/209857046-83936819-35a6-4c37-8957-4534bb85bef4.png)
The theory written by Georgios N. Konstantinou, seems to be the most used nowadays, at least in Greece and Romania
I think it would be better to use as default
* hardChromaticScale = [6, 18, 6, 12, 6, 18, 6];
* softChromaticScale = [8, 16, 6, 12, 8, 16, 6];
