### ISSUE TITLE
[ENHANCEMENT] Out of Scale range

### ISSUE THREAD

**Issue by efraimkaov** [danielgarthur/neanes#43]
Happy Birthday! Thanks again for your wonderful work and may God bless you and all your work.
I want to ask you to add restriction when you go out of range of each Scale.
A warning message would be perfect.

**Comment by danielgarthur** [comment]
I recently added the note names to the bottom toolbar when a neume is selected (bottom left of the toolbar). If the note is outside of the normal range of Byzantine chant (low vou - high ke), then `???` is displayed.

Is this what you mean? If not could you please describe in more details what you mean by "out of range of each Scale"?

**Comment by efraimkaov** [comment]
Sorry for my bad English!
I am a beginner in Byzantine music theory as well.
I have the [Melodos](https://www.melodos.com/) as a reference, which is a good program, but very expensive.
Only those who make money from the sale of musical scores could give such a large amount of money for this program.
I like free and open source and even if I'm not a programmer, I had the idea to make a kind of clone of **Melodos**.
I was not interested in writing musical scores but in playing them.
The details from bottom toolbar is more than enough, I have not noticed.
There are different limits for each **Mode**.
In these images you have an example from **Melodos** for **First Mode**, I hope it clarifies what I wanted to say
![mel1](https://user-images.githubusercontent.com/63643635/210247787-5e78bcf6-ba1c-45b2-a22e-6de6dbf3441a.png)
![mel2](https://user-images.githubusercontent.com/63643635/210247806-395c4f37-942b-488d-9c05-059503cc6903.png)
![mel3](https://user-images.githubusercontent.com/63643635/210247823-7c754a3d-7433-4c22-bccf-3de50780a6ac.png)
![mel4](https://user-images.githubusercontent.com/63643635/210247840-7f122d8e-87d2-41d5-8a55-d526cc2e08ef.png)
