### ISSUE TITLE
Too much whitespace around vareia

### ISSUE THREAD

**Issue by PsaltyDog** [danielgarthur/neanes#45]
Merry Christmas, Happy New Year, and Blessed Theophany, all in one go!

I've been noticing that the vareia seems to have an issue with whitespace: It seems to interpret the amount of overhang of a word over the neume as the amount of space to be left from the previous neume to the vareia. I'm not sure, but I think it may even leave a bit more space after the neume with the vareia as well.

![evil problem](https://user-images.githubusercontent.com/116736628/211257514-b525b730-f8e1-4f05-8c4d-1e251d4b536c.jpg)

Forgive me if my description doesn't make sense!

**Comment by danielgarthur** [comment]
This should be fixed now. Hopefully the fix didn't break anything else. I spot-checked with various files and they all still looked correct.

As for the whitespace after the character with the vareia, it is currently "working as expected" (or at least it is after the latest fix). However, perhaps there is an improvement that could made: if there is a melisma, then the second apostrofos doesn't really need to be adjusted to the right. I'd have to think through the exact rules more carefully.

**Comment by PsaltyDog** [comment]
Looks great now. Thank you.

I wonder if it wouldn't be more useful to have it only add extra space between the neumes if the words collide, rather than having it avoid the word boundaries. That way it would also avoid things like:

![evil spacing issue](https://user-images.githubusercontent.com/116736628/211626881-3e38c3f3-a950-47c8-a2e4-c48ee5fc965d.jpg)

Basically, to have it avoid overlap between neumes and neumes and between text and text, but not between neumes and text.

**Comment by danielgarthur** [comment]
I think that's a great idea and I've just pushed a release that does that. It's kind of a big change, so I hope I covered all the cases. Again, I spot-checked with a bunch of files, but there may be some situation that I missed. Let me know how it looks.

**Comment by PsaltyDog** [comment]
Nice. Thanks, this is a lot easier to work with. Things I've noticed:

1) 'spacing after' takes as its base position the position of the neume without any adjustment for Lyrics H, so if you have a long syllable and you want to add more space after it, you have to increase 'spacing after' to the point to which it already has been adjusted automatically, and only then do you start to see it move.

2) 'spacing after' also doesn't allow you to decrease the spacing beyond the Lyrics H setting. I can imagine a couple scenarios when someone might want to do this; for instance, if someone wanted to run two syllables of a word together to have them display as in normal text:
![evil spacing3](https://user-images.githubusercontent.com/116736628/212007091-95150b4d-1c38-4233-b153-0bf7a108d837.jpg)
(this is from an old score made with EZ Psaltica, which I am grateful I no longer have to deal with; it was a Godsend at the time, but this program is much easier to work with)
3) word extenders are treated by the program as lyrics, so it doesn't allow any overlap with the following text:
![evil spacing1](https://user-images.githubusercontent.com/116736628/212006401-c9963f9e-31df-48f1-bf62-e5e3e017b2f6.jpg)
versus:
![evil spacing2](https://user-images.githubusercontent.com/116736628/212006442-2dd7e181-9da3-4087-951e-82ef518305da.jpg)

**Comment by danielgarthur** [comment]
The Spacing After has been fixed, and words can now take up some space from the previous melisma.

![image](https://user-images.githubusercontent.com/4132779/212438592-08474e75-ad3f-4045-9a17-a6331ad527a4.png)

**Comment by PsaltyDog** [comment]
Very nice. Thank you!

**Comment by PsaltyDog** [comment]
So, the only thing I've noticed regarding this issue now that I think could be improved, is that it's spacing for text even when there's a melisma, for example:

[spacing.byz](https://github.com/PsaltyDog/Stuff/raw/main/spacing.byz)
[spacing.pdf](https://github.com/PsaltyDog/Stuff/raw/main/spacing.pdf)

The program doesn't seem to ever allow text to overlap with the centre of the following neume. This behaviour makes sense when this belongs to a different syllable, but otherwise it just creates an unexplained whitespace.

By the way, you can only attach certain file types to a comment on github, of which neither byz nor pdf is one. That's why I'm uploading them in this odd way.

**Comment by danielgarthur** [comment]
Upload test
[UploadTest.zip](https://github.com/danielgarthur/neanes/files/10421258/UploadTest.zip)

**Comment by danielgarthur** [comment]
Zipping the byz file and uploading the zip file works. I've just updated the bug report template to include information about uploading byz files.

Also, the melisma spacing issue should be fixed.

**Comment by PsaltyDog** [comment]
Aha! Yes, makes sense. I'll do that from now on.

Thank you!
