### ISSUE TITLE
[BUG] Image placement in pdf

### ISSUE THREAD

**Issue by dimii27** [danielgarthur/neanes#466]
**This bug was found in**

- [x] Desktop
- [ ] Web App
- [ ] Both

Sometimes images are not placed correctly in the pdf export

I am not sure how to reproduce this because I just adjust the size of an image and it suddently exports as expected

![image](https://github.com/danielgarthur/neanes/assets/50188164/fa41c99a-96f2-47a1-98a6-74e804034389)

![image](https://github.com/danielgarthur/neanes/assets/50188164/940577a3-a62f-4ba2-8dc1-daaa4bf327bc)

**Comment by dimii27** [comment]
A quick and efficient fix is to insert a line break in the title box. This action apparently does nothing but it solves the described bug in this issue.

**Comment by danielgarthur** [comment]
I was able to reproduce this by setting zoom to 50%, as in your first screenshot. I'm investigating.
