### ISSUE TITLE
[BUG] Line extenders overshooting their last neume

### ISSUE THREAD

**Issue by PsaltyDog** [danielgarthur/neanes#47]
**This bug was found in**
- [x] Desktop

**Describe the bug**
So, this doesn't seem to be a new bug, although I've only noticed it now. Sometimes line extenders are longer than they need to be, and sometimes they even go into the next word. This happens a lot more in PDF than in the program.

The first example of this that I can find among my scores is from 29/12/2022, but I don't export to PDF very often, so it may have come up before then. It doesn't seem to have been there from the beginning, but it's hard to be sure, because it doesn't happen in all cases.

I've attached screenshots both from the program and from a PDF of the same score. In the program, I've drawn red arrows pointing to the affected extenders. In PDF, nearly every one is affected.

Program:
![evil problem](https://user-images.githubusercontent.com/116736628/212467224-f1c27da6-9eb5-47df-9f8f-17d869f96803.jpg)

PDF:
![evil problempdf](https://user-images.githubusercontent.com/116736628/212467234-9dd883df-0883-4ce4-a14e-0e6ee6d35dcd.jpg)

**Comment by danielgarthur** [comment]
Could you please attach the byz or byzx file and the PDF?

**Comment by PsaltyDog** [comment]
Here they are.

[byz](https://github.com/PsaltyDog/Stuff/raw/main/Meeting%20Stichera.byz)
[pdf](https://github.com/PsaltyDog/Stuff/raw/main/Meeting%20Stichera.pdf)

**Comment by danielgarthur** [comment]
I am unable to access them. I think you can drag and drop the files into the comments box to upload them directly, instead of linking to them.

However, I found a bug that was recently introduced on Dec. 1. I'll create a release in a couple minutes, which I think fixes this issue.

**Comment by PsaltyDog** [comment]
My bad. You should be able to access them now, if you need to.

**Comment by PsaltyDog** [comment]
I checked the score now, and the PDF version is almost entirely fixed, but there still remain in both the BYZ and the PDF the three cases that I pointed to in the first image.

**Comment by PsaltyDog** [comment]
There seems to be an issue with vareia for two of the cases. I've tried the same example with and without vareia:

![evil prob](https://user-images.githubusercontent.com/116736628/212499645-5a503a46-f5c9-4172-8c2e-41000a9daec3.jpg)

**Comment by PsaltyDog** [comment]
I've messed around with it a bit, and all cases seem to be linked to text overhanging a neume with vareia, either preceded or followed by a line extender.

**Comment by danielgarthur** [comment]
Thanks, the file helped. It was, as you suggested, an issue with not properly taking into account the width of the vareia in certain calculations.

**Comment by PsaltyDog** [comment]
Thank you! Seems to be working properly now.
