### ISSUE TITLE
Spathi on Ga

### ISSUE THREAD

**Issue by PsaltyDog** [danielgarthur/neanes#48]
I notice that you've set the spathi to only be allowed on Ke. I've never actually seen this that I can remember, but I have read in more than one book that it can also be used on Ga. I've attached a couple examples. Forgive me, I don't read Greek, so I can't give any source in Greek.

Chrysanthamos (he doesn't mention any note in particular, but the example is on Ga):
![Chrysanthamos](https://user-images.githubusercontent.com/116736628/213156573-a02d026a-ad5a-43ac-b539-8732d6615bb7.jpg)

Savas Savas:
![Savas Savas](https://user-images.githubusercontent.com/116736628/213156611-60623402-0d11-4be3-97e4-6563d1798111.jpg)

David Melling:
![Melling](https://user-images.githubusercontent.com/116736628/213156641-b06b8603-28bf-4b19-999b-4e7744a7c08e.jpg)

**Comment by danielgarthur** [comment]
I've also never seen the Spathi above Ga, although I've read that it is possible. The main reason that I haven't implemented the Spathi above Ga is that I do not know the correct martyria signs. In the picture from David Melling, you can see the martyria for the Spathi over Ke, but the martryia when it's over Ga are missing. The intervals are different, so the martyria may not be the same. I could try and guess the martyria, but I'd rather have a source reference. 

I can look through some Greek theoretical books to see if I can find them.

**Comment by danielgarthur** [comment]
Found [this](https://analogion.com/forum/index.php?threads/%CE%A3%CF%80%CE%AC%CE%B8%CE%B7-%CF%83%CF%84%CE%BF%CE%BD-%CE%93%CE%B1.19239/) on Psaltologion. I'll have to read through it later and see if anyone came up with a good answer.

**Comment by danielgarthur** [comment]
I actually found an example in some music that I have! Before now, I had always misread it as a soft chromatic fthora.

<img width="599" alt="image" src="https://user-images.githubusercontent.com/4132779/213271636-abdd65df-5229-45d2-aa9c-175dbc7db537.png">

**Comment by danielgarthur** [comment]
There didn't really seem to be a definite conclusion and some were saying that the melody would never pause on any note except Ga (for which the martyria is already known), so it doesn't really matter what the other martyria around it are.

I think that's probably true, so I've gone ahead and added the Spathi over Ga. I used the martryia from the images [here](http://analogion.com/forum/index.php?threads/%CE%A3%CF%80%CE%AC%CE%B8%CE%B7-%CF%83%CF%84%CE%BF%CE%BD-%CE%93%CE%B1.19239/post-124418), which seem reasonable to me.

Ζαχαρίας Πασχαλίδης, Ἐκκλησιαστικὴ Βυζαντινὴ Μουσική, Σύντομη θεωρία καὶ πράξη, Θεσσαλονίκη 1985.
![image](https://user-images.githubusercontent.com/4132779/213350731-6802e427-0bdc-42da-b334-c9b266bb4d59.png)

**Comment by PsaltyDog** [comment]
Thanks. Yeah, that all makes sense. For that matter, I don't know that I've seen spathi on Ke rest on any other note than Ke in real music, though I imagine it must, since the theory books give martyria for the others.
