### ISSUE TITLE
[ENHANCEMENT] Auto Update for macOS

### ISSUE THREAD

**Issue by t-bullock** [danielgarthur/neanes#56]
Any chance we could get an auto update feature in Neanes?

https://www.electronjs.org/docs/latest/tutorial/updates

I'm recommending this program to some non-technical friends who don't know about Github or downloading releases. Even though it's still in alpha, Neanes is much better and faster than typing scores using the EZ fonts in a word processor.

**Comment by danielgarthur** [comment]
Auto-update currently works with Windows and Linux. The issue with auto-update on Mac is that it requires builds to be code signed. As far as I know, the only way to get a code signing certificate is to give Apple $100 every year for as long as I'm making builds. And at that point, I might as well sign the Windows build, too, which is another yearly fee.

If you have any experience with this, and I'm missing some other option, please let me know. 

Code signing would also have the benefit that the operating system would stop showing all those warnings about "unsigned software" when you are trying to install it or run it. So it would be nice to have.

**Comment by danielgarthur** [comment]
For the time being, I will look into seeing if I can at least show a notification for Mac users with a download link, but they will have to download and install the update themselves.

**Comment by danielgarthur** [comment]
The notification has been added to the latest release, but it is not auto-download.

**Comment by t-bullock** [comment]
> For the time being, I will look into seeing if I can at least show a notification for Mac users with a download link, but they will have to download and install the update themselves.

I don't have any experience with it unfortunately, but getting a license through Apple and all that will be a hassle. This seems like a good solution for now.
