### ISSUE TITLE
[BUG] disappearing hyphen

### ISSUE THREAD

**Issue by PsaltyDog** [danielgarthur/neanes#57]
**This bug was found in**

- [x] Desktop

**Describe the bug**
When the neumes are narrower than the text, the hyphen disappears and there's just a space left:
![disappearing hypehn](https://user-images.githubusercontent.com/116736628/218321137-3b641f63-53d4-4b69-a34e-1bb9571daf2b.jpg)
[disappearing hyphens.zip](https://github.com/danielgarthur/neanes/files/10716468/disappearing.hyphens.zip)

**Comment by danielgarthur** [comment]
Fixed by 4cbf8c1.

**Comment by PsaltyDog** [comment]
Forgive me, for some reason this one has resurfaced:

![hyphen](https://user-images.githubusercontent.com/116736628/220983288-0e6c96df-4c27-4b71-8f69-fe661fab7dad.jpg)
[hyphen.zip](https://github.com/danielgarthur/neanes/files/10816385/hyphen.zip)

There's a hyphen between the two, but it doesn't display.

**Comment by danielgarthur** [comment]
I think this is fixed now.
