### ISSUE TITLE
[ENHANCEMENT] Allow fthores above the apostrofos in a syneches elafron

### ISSUE THREAD

**Issue by psarsama** [danielgarthur/neanes#61]
**Is your feature request related to a problem? Please describe.**
As a composer working with diatonic and enharmonic scales with scores that include the continuous elaphron, I want to be able to add the ajem to continous elaphron when the right note is included in _either_ position of the continuous elaphron.

**Describe the solution you'd like**
When the first of the two notes in a continuous elaphron is Ζο or Βου, I would like the ajem to be able to be added to it. If the continuous elaphron is from Γα to Βου, the user should have the ability to determine whether the ajem belongs over one note or the other (e.g., when user clicks ajem symbol once, it appears over Γα; if user clicks again, it moves to Βου). 

**Describe alternatives you've considered**
There aren't tidy solutions for manual intervention apart from exporting as PDF and manually adding.

**Comment by PsaltyDog** [comment]
Same issue exists with the other combination neumes: hyporrhoe, continuous elaphron with petasti, and all combinations with kentimata.

**Comment by danielgarthur** [comment]
> Same issue exists with the other combination neumes: hyporrhoe, continuous elaphron with petasti, and all combinations with kentimata.

How does this apply to the yporroi? Do you mean for audio playback?

**Comment by danielgarthur** [comment]
> There aren't tidy solutions for manual intervention apart from exporting as PDF and manually adding.

As a temporary workaround, if you only need to move a single mark, then you an use the [positioning dialog](https://danielgarthur.github.io/neanes/guide/advanced.html#fine-tuning-neume-positions) to move the mark from the elafron to the apostrofos. 

Adding the ability to more easily select which neume the mark goes over, or allowing multiple marks will take some more time.

**Comment by PsaltyDog** [comment]
> How does this apply to the yporroi? Do you mean for audio playback?

It's because the agem fthora (among others) is only permitted on certain notes, but if an yporrhoe passes through Zo for instance and lands on Ke, then the program only recognizes the Ke and will not permit agem. Here's a hypothetical example (in Third Tone):

![mo agem](https://user-images.githubusercontent.com/116736628/219870105-7eae0bb0-be2f-413a-8e05-3d1a2add19a4.jpg)
[mo agem.zip](https://github.com/danielgarthur/neanes/files/10774441/mo.agem.zip)

In the second example I have done what you said and put the agem on the last Zo and manually postitioned it over the yporrhoe, which does work, but it has to be redone every time any changes are made to the score that cause neumes to be repositioned here.

**Comment by psarsama** [comment]
> As a temporary workaround, if you only need to move a single mark, then you can use the [positioning dialog](https://danielgarthur.github.io/neanes/guide/advanced.html#fine-tuning-neume-positions) to move the mark from the elafron to the apostrofos.

Good call on positioning; I was thinking in terms of playback as well, but that's less important (to me) than the compositional aspect.

**Comment by danielgarthur** [comment]
As part of the `0.3.0-beta.7` the app now keeps track of all notes that are traversed by a single neume. This means that you can now place the enharmonic fthora on a neume that passes through ZO, even if it does not land on ZO.

If the neume passes through both GA and VOU, then a dropdown appears in the bottom toolbar that allows you to select which note you want the fthora to apply to when playing audio.

In the case of a syneches elafron, you will still need to manually position the fthora with the positioning dialog, as automatic positioning is not yet supported in this case. Note that positioning the fthora does NOT affect audio playback. To get the correct playback, you must choose which note you want the fthora to apply to, as described above.

**Comment by danielgarthur** [comment]
Version `0.3.0-beta.12` now includes a neume selector in the neume toolbar. This can be used to choose which neume the gorgon, fthora, or accidental should appear above. Audio playback has not yet been updated to support this new feature.

<img width="263" alt="image" src="https://user-images.githubusercontent.com/4132779/235835972-716e309f-a076-4343-8393-cf9d909a2b6e.png">
