### ISSUE TITLE
[ENHANCEMENT] Keyboard shortcut to toggle between lyrics and neumes

### ISSUE THREAD

**Issue by psarsama** [danielgarthur/neanes#62]
**Is your feature request related to a problem? Please describe.**
When setting words to a score, it would be good to quickly bounce back and forth from entering lyrics to entering/editing notation.

**Describe the solution you'd like**
When user is entering neumes, if the user presses "down" arrow, then the user should be able to enter text under the neume.
When user is entering text, if the user presses "up" arrow, then the user should be able to enter/edit the neumes directly above the text he/she was entering.

**Describe alternatives you've considered**
A keyboard shortcut to switch to text editing mode / neume editing mode. E.g., Ctrl+T to switch between the two.

**Comment by danielgarthur** [comment]
Added to latest release. Use <kbd>Ctrl</kbd>+<kbd>Up Arrow</kbd> and <kbd>Ctrl</kbd>+<kbd>Down Arrow</kbd> to move between the neume and its lyrics.
