### ISSUE TITLE
combined apostrophe+kentimata over oligon with gorgon to both neumes?

### ISSUE THREAD

**Issue by AnK58** [danielgarthur/neanes#63]
**This bug was found in**

- [x] Desktop
- [ ] Web App
- [ ] Both

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots or files**
If applicable, add screenshots to help explain your problem. You may also upload a `byz` or `byzx` file, but you must first zip it and upload the `zip` file.

**Desktop Version (please complete the following information, if applicable):**

- OS: [e.g. Windows 10, macOS 12]
- Version [go to Help > About]

**Web App (please complete the following information, if applicable):**
Note: That the web app version currently only supports Chromium-based browsers. Mobile devices are not currently supported. Please do not file a bug if not using an unsupported browser or a mobile device.

- Browser [e.g. Chrome, Edge]
- Version [go to Help > About]

**Additional context**

**Comment by AnK58** [comment]
combined apostrophe+kentimata, (and all double neumes) over oligon with gorgon to both neumes is impossible.
However I tried it was impossible to put gorgon to both neumes. It only goes to kentimata.

**Comment by danielgarthur** [comment]
This is not documented as well as it should be, but it is possible. If you click on the apostrophe + kentimata in the neume selector in the left, and hold down the mouse button, a menu will appear that allows you to select which gorgon you want over the apostrofos.
![image](https://user-images.githubusercontent.com/4132779/219970357-ae647f17-2abb-46a3-86e5-ecda834f58da.png)

This is currently supported for what I think are the most common cases for double neumes needing a gorgon.

- ison + kentimata
- apostrofos + kentimata
- yporroi + kentimata

 The feature should probably be expanded to cover the less common cases like the elafron + kentimata and hypsili + kentimata.

**Comment by danielgarthur** [comment]
I think adding some kind of indicator that more options are available for those neumes would be helpful, too.

**Comment by danielgarthur** [comment]
Added to the latest release. Click and hold the following neumes to add secondary gorgons:

- Ison +Kentemata
- Apostrofos + Kentemata
- Elafron + Kentemata
- Elafron + Apostrophos + Kentemata
- Syneches Elafron + Kentemata
- Chamili + Kentemata
- Yporroi + Kentemata

**Comment by AnK58** [comment]
Many thanks. Your response was of great help.
________________________________
Από: danielgarthur ***@***.***>
Στάλθηκε: Κυριακή, 19 Φεβρουαρίου 2023 7:25 μμ
Προς: danielgarthur/neanes ***@***.***>
Κοιν.: AnK58 ***@***.***>; Author ***@***.***>
Θέμα: Re: [danielgarthur/neanes] combined apostrophe+kentimata over oligon with gorgon to both neumes? (Issue #63)


This is not documented as well as it should be, but it is possible. If you click on the apostrophe + kentimata in the neume selector in the left, and hold down the mouse button, a menu will appear that allows you to select which gorgon you want over the apostrofos.
[image]<https://user-images.githubusercontent.com/4132779/219970357-ae647f17-2abb-46a3-86e5-ecda834f58da.png>

This is currently supported for what I think are the most common cases for double neumes needing a gorgon.

  *   ison + kentimata
  *   apostrofos + kentimata
  *   yporroi + kentimata

The feature should probably be expanded to cover the less common cases like the elafron + kentimata and hypsili + kentimata.
