### ISSUE TITLE
[BUG] hyphen and line extender issue

### ISSUE THREAD

**Issue by PsaltyDog** [danielgarthur/neanes#66]
**This bug was found in**

- [x] Desktop

**Describe the bug**
So, when a hyphen or line extender is placed between two syllables, they no longer overlap, nor will it allow you to manually overlap them. 

![issue](https://user-images.githubusercontent.com/116736628/220981203-0a4cb07d-ef98-46f0-a0ca-97b55f4b852d.jpg)
[issue.zip](https://github.com/danielgarthur/neanes/files/10816329/issue.zip)

When a space is between them, it overlaps as normal. 

Thank you for all the work you've put into this program!

**Comment by danielgarthur** [comment]
I think this is fixed now in the latest release along with #57. I also checked that #58 is still working.
