### ISSUE TITLE
[BUG] Hyphen displaying too far to the right

### ISSUE THREAD

**Issue by PsaltyDog** [danielgarthur/neanes#70]
**This bug was found in**

- [x] Desktop

**Describe the bug**
Sorry, the hyphen is doing that thing again where it displays too far to the right. It doesn't do it in all cases, but I can't tell what circumstances cause it. It itself doesn't bother me so much, but it seems to also hold the neumes apart a little bit more than they need to be.

![hyphens](https://user-images.githubusercontent.com/116736628/224162039-799c561d-ec88-4597-b105-5787382edb44.jpg)
[hyphens.zip](https://github.com/danielgarthur/neanes/files/10936122/hyphens.zip)

**Comment by danielgarthur** [comment]
Fixed in `0.3.0-beta.15`.
