### ISSUE TITLE
[BUG] File not exporting to PDF correctly

### ISSUE THREAD

**Issue by LeSniffa** [danielgarthur/neanes#71]
When I exported my latest project to pdf I noticed that in the later pages the text seems to be misplaced.

![image](https://user-images.githubusercontent.com/110656129/224413595-d469528e-99e5-4c3a-956f-1008b24ccd94.png)
The very start of a page

![image](https://user-images.githubusercontent.com/110656129/224413690-1abec21c-4ff6-4ec1-bfe8-f9817f3495f3.png)
The end of the same page

It appears that for some reason everything has shifted up.

**Comment by danielgarthur** [comment]
Could you please ZIP up the `.byz` file and post it here?

**Comment by LeSniffa** [comment]
[παρακληση.zip](https://github.com/danielgarthur/neanes/files/10947995/default.zip)

**Comment by danielgarthur** [comment]
This should be fixed now in the latest release.
