### ISSUE TITLE
[ENHANCEMENT] Insert Images 

### ISSUE THREAD

**Issue by Cityyankee24** [danielgarthur/neanes#78]
Ability to add images to scores, example: Icon at bottom of score, Byzantine art at header level above title, etc.

**Comment by danielgarthur** [comment]
Added to release 0.3.0-beta.10.
<img width="575" alt="image" src="https://user-images.githubusercontent.com/4132779/229264810-4a9efc65-d655-4eb5-8957-1e51ead6c120.png">
