### ISSUE TITLE
[ENHANCEMENT] Fthora limitations lifted

### ISSUE THREAD

**Issue by TugleaCristian01** [danielgarthur/neanes#80]
**Is your feature request related to a problem? Please describe.**
Yes. I was transcribinng a sheet that had a Zygos fthora on Zo, and the rules of the fthora didn't allow me to introduce it, so I had to place manually attractions.

**Describe the solution you'd like**
I think it would be best to select if you want fthora rules to apply to a sheet, or not. 

**Describe alternatives you've considered**
Eliminating the rules at all, though they may be useful for someone who doesn't know them and is writing sheets

**Additional context**
None

**Comment by danielgarthur** [comment]
Giving the users the option to disable the normal fthora rules is an option, but my concern is the calculation of martyria. This came up in #48, too. If chroa are allowed anywhere, then it's not always clear what the correct martyria should be when placed in non-standard locations.

While it's unlikely that a martyria will appear while the chroa is in effect, it could happen. One option could be to allow users in this case to create their own custom martyria by selecting whatever root sign they want.

**Comment by TugleaCristian01** [comment]
This is a romanian theory book that I read and it's accurate in all other matters. About Zygos fthora it says that it changes the martyria below it to Necheanes (as the one from chromatic Pa), and the one above it no Nana (as from normal Ga). All other martyrias are kept the same. The book says this for Ke, but specifies that it is available for all other notes. It may be a solution, if you want to consider it. Allowing the user to choose the martyria he wants is another.
![InkedWhatsApp Image 2023-04-01 at 20 33 54](https://user-images.githubusercontent.com/129614034/229306272-568ba9fd-eecc-410c-b268-83d6a26e6c25.jpg)

**Comment by PsaltyDog** [comment]
> Allowing the user to choose the martyria he wants is another.

Or maybe even just force the user to choose the martyria if he's using a fthora in a non-standard way?

**Comment by danielgarthur** [comment]
The option to disable fthora restrictions has been added to `0.3.0-beta.16`.

Go to Page Setup and check the "Disable Fthora Restrictions" checkbox.
<img width="407" alt="image" src="https://github.com/danielgarthur/neanes/assets/4132779/1c627fde-0f3d-4878-9d40-e179b294e404">

All restrictions will be lifted. Audio playback may not properly playback the correct scales if fthores are in non-standard positions.
<img width="458" alt="image" src="https://github.com/danielgarthur/neanes/assets/4132779/010cf7db-921a-480b-a248-399900a58e2d">

If you want to change the root sign on a martyria, you can use the "Root Sign Override" dropdown in the bottom martyria toolbar. In this screenshot I have changed the root sign to Varys to demonstrate the feature.
<img width="236" alt="image" src="https://github.com/danielgarthur/neanes/assets/4132779/030dbd5f-f165-4055-902f-7aa68cf83b8e">
