### ISSUE TITLE
Adding range at the beggining of a sheet

### ISSUE THREAD

**Issue by TugleaCristian01** [danielgarthur/neanes#82]
Christ is Risen!

I think it would be a great feature for the app (especially for those singing the sheets), if the ambitus (range) of the melody could be automatically calculated and added at the beginning of a sheet (as a preference). It would be great also if the martyria displayed in the ambitus stays true to sheet if there is a phtora placed before it. But still, even just displaying the range with diatonic martyrias is great too!

![Adding range idea](https://user-images.githubusercontent.com/129614034/234509220-9c6ef3f2-26e5-4bb8-88e3-9e695e7559b9.jpg)

Thank you!

**Comment by danielgarthur** [comment]
Added to release `0.3.0-beta.11`.

**Notes**

- The ambitus takes into account fthores, but if the same highest note is reached with two different martyria, the last one wins.
- No distinction is made between exact pitch. For example, hard chromatic high NI has a higher pitch than diatonic NI. If both notes are reached, then the last martyria is chosen, even if it is not truly the highest pitch.
