### ISSUE TITLE
[ENHANCEMENT] Fthora and Accidental Above Kentimata Combos

### ISSUE THREAD

**Issue by asajkeim** [danielgarthur/neanes#85]
**Is your feature request related to a problem? Please describe.**
I'm transcribing music from Simonopetra's books, and whether it's correct or not, they occasionally put fthores and accidentals on the first neume of an oligon-united sequence (such as an oligon with an apostrophos and kentimata on top), but in Neanes, the fthora or accidental will only apply to the second thing (kentimata) and not the first.

**Describe the solution you'd like**
It seems like there could just be a way to switch the item, either moving the position or simply changing what note it affects. Hope this can happen!

**Comment by danielgarthur** [comment]
I've been putting together a plan for the past week or so on how to fix this, as it's a known issue. There is only one thing that I am unsure of. Where should the diesis be placed? If it goes under the oligon, then it seems like it would be ambiguous. If you have some examples from some books on how this should be written, that would be really helpful. 

For example, where should the diesis be placed in these cases:

<img width="95" alt="image" src="https://user-images.githubusercontent.com/4132779/235723115-f94eb401-cf30-4186-9384-cc51def28425.png">

In the second case, the diesis could potentially affect three different notes. I'm not sure where the proper placement should be.

**Comment by danielgarthur** [comment]
Version `0.3.0-beta.12` now includes a neume selector in the neume toolbar. This can be used to choose which neume the gorgon, fthora, or accidental should appear above. Audio playback has not yet been updated to support this new feature.

<img width="263" alt="image" src="https://user-images.githubusercontent.com/4132779/235835972-716e309f-a076-4343-8393-cf9d909a2b6e.png">
