### ISSUE TITLE
[ENHANCEMENT] Large projects page counting

### ISSUE THREAD

**Issue by TugleaCristian01** [danielgarthur/neanes#88]
Hello!

I'm currently working on a project that implies more pages, and I think it would be a useful feature one that allows controlling the page numbers, in order to label correctly more pdfs. I can think of two solutions for that:

1. An option to choose from what number does the page counting starts.
2. Creating a $*number* variable so that when you type it on a footer it starts counting the pages from that number (for example typing $5 will start counting the pages from number 5)

Thank you!

**Comment by danielgarthur** [comment]
Would adding a "first page number" to the Page Setup be enough? Something like Musescore's feature described [here](https://musescore.org/en/handbook/3/page-settings#first-page)?

Or do you want to be able to skip page numbers in multiple places within the same file?

**Comment by TugleaCristian01** [comment]
I think that the „first page number” option is enough. Thank you!

**Comment by danielgarthur** [comment]
Added to `0.3.0-beta.18`.
