### ISSUE TITLE
[BUG] Cannot insert gorgon on yporroe with petaste

### ISSUE THREAD

**Issue by basil** [danielgarthur/neanes#89]
### Preface

Many thanks for this excellent piece of software.

### Context

This bug was found in:

- [ ] Desktop
- [ ] Web App
- [x] Both

### Describe the bug

[Orthographic rule № 106](https://music.samonastery.org/ByzOrthography.pdf) clearly shows that it is valid for an yporroe with a petaste to have a gorgon.

On an yporroe with a petaste, the gorgon button is not grayed out, but attempting to add a gorgon has no effect.

### To Reproduce

1. Create a blank score.
2. Press Shift + D + M to create an yporroe with a petaste.
3. Press G to add a gorgon.

### Expected behavior

A gorgon appears.

### Actual behavior

Nothing happens.

### Desktop Version

- OS: Ubuntu 22.04.2 LTS x86_64
- Version: 0.3.0-beta.18

**Comment by danielgarthur** [comment]
Fixed in `0.3.0-beta.19`.

**Comment by basil** [comment]
Thank you very much!
