### ISSUE TITLE
Project dependencies are several years out-of-date

### ISSUE THREAD

**Issue by basil** [danielgarthur/neanes#93]
The project's dependency tree dates back to approximately 2019, which is apparently when the project was begun. While e.g. https://github.com/nklayman/vue-cli-plugin-electron-builder/issues/1959 precludes an upgrade to the very latest packages (like Node 18 and Electron 23), upgrading packages to relatively recent (as opposed to years-old) versions improves the developer experience (by making it easier to access documentation), increases portability (by making it more likely the project will compile on recent build environments), and reduces the risk of consuming vulnerable packages. Upgrading these old dependencies should be done incrementally (in small chunks) in order to ensure that proper testing is done and no regressions occur.

**Comment by danielgarthur** [comment]
If you're looking at linting, please checkout the linting docs for prettier [here ](https://prettier.io/docs/en/integrating-with-linters.html) and [this library](https://github.com/prettier/eslint-config-prettier) to see whether this would be a good option.

**Comment by basil** [comment]
> please checkout the linting docs for […] [this library](https://github.com/prettier/eslint-config-prettier) to see whether this would be a good option

I already use `esconfig-lint-prettier` in [one of my other projects](https://github.com/jenkinsci/jenkins/blob/db925bb1bffe51168d9843b0a85e2148758c5fce/war/package.json#L35). It is a good option.
