### ISSUE TITLE
`git status` is not clean after following instructions on a new computer

### ISSUE THREAD

**Issue by basil** [danielgarthur/neanes#99]
### Steps to reproduce

- Follow the instructions to build the project in the `README`.
- Run `git status`.

### Expected results

`git status` is clean.

### Actual results

`git status` shows a dirty `package-lock.json`.

### Notes

In https://github.com/danielgarthur/neanes/pull/92#issuecomment-1550253036 @danielgarthur wrote:

> My expectation would be that developers use `npm install`. If this results in a change to `package-lock.json`, then this would committed as part of the PR. But there should never be a PR that is purely to update package-lock.json.

This would make sense if and only if there was a rule that any change to `package.json` must also be accompanied by running `npm install` and checking in the updated `package-lock.json`. But such a rule is not in place, as evidenced by commit 58fcde4. The fact that such a rule is not in place means that someone making an unrelated change (or simply running the build on a new computer) will end up with unrelated changes to `package-lock.json` and a broken `git status`, which in turn will result in `git commit -a` being broken and likely negative feedback in code reviews. _Valid_ solutions to this problem include:

- #91 Continue to use `npm install` as the supported mechanism in the `README`, but _also_ require that any changes to `package.json` be accompanied by `npm install` and checking in an updated `package-lock.json`. This ensures that `git status` is always clean.
- #92 Maintain the existing laxity around updating `package-lock.json` but change the `README` to recommend `npm ci` instead.

> I would consider this standard practice

It is not the standard practice in another project I maintain which has significantly more developers than this one.

**Comment by danielgarthur** [comment]
Could you list some example repos that I could check out to see how they are doing things? Like are they saying to use npm ci in development setup guides? Or being more specific about Node versions requirements? Etc.
